Support simpler capture and replay of ValidatorInputs
There are several changes in this commit.

1. Move the `parse_inputs.rs` and `prepare.rs` files from the benchbin
package to the prover. This enables the prover to ingest most of the
information it needs from the `block_inputs_<id>.json` file.

2. Add a `--json-inputs` flag to the `prover` bin which obviates
several competing flags preferring to read the data from the json.

3. Write the json file to disk in the working directory before the
arbitrator spawner writes the `run_prover.sh` file which is attempting
to make a similar validaiton easy to reproduce.

4. Introduce a new `recordBlock` method to the tests suite which can be
called once a block has been recorded to L1.

5. Wire the call to `recordBlock` into the `TestProgramStorage` to be
sure to capture a block that actually uses a Stylus contract so that
the prover can be shown to work with that block as well.

6. Enhance the `parse_inputs.rs` to know how to handle the `UserWasms`
deserialization.

To reproduce the failure state at this commit:
1. make clean && make all
2. go test -timeout 10m -tags challengetest -run ^TestProgramStorage$ github.com/offchainlabs/nitro/system_tests
3. Observe, there are now two new files in `ls system_tests/block_inputs_{2,5}.json`
4. target/bin/prover target/machines/latest/machine.wavm.br -b --json-inputs system_tests/block_inputs_5.json
5. The error is:
```
thread 'main' panicked at prover/src/machine.rs:690:58:
unknown dictionary: TryFromPrimitiveError { number: 10 }
```

If you make changes to the rust code, you can quickly rebuild and install with:
```
cargo build --manifest-path arbitrator/Cargo.toml --release --bin prover && install arbitrator/target/release/prover target/bin/prover
```